find_path(STB_INCLUDE_DIR NAMES stb.h PATHS {CONAN_INCLUDE_DIRS_STB} NO_CMAKE_FIND_ROOT_PATH)
# find_library(STB_LIBRARY NAMES ${CONAN_LIBS_STB} PATHS ${CONAN_LIB_DIRS_STB} NO_CMAKE_FIND_ROOT_PATH)

message(STATUS "** STB ALREADY FOUND BY CONAN!")
# message(STATUS "** FOUND STB: ${STB_LIBRARY}")
message(STATUS "** FOUND STB INCLUDE: ${STB_INCLUDE_DIR}")

set(STB_FOUND TRUE)
set(STB_INCLUDE_DIRS ${STB_INCLUDE_DIR})
# set(STB_LIBRARIES ${STB_LIBRARY})

# mark_as_advanced(STB_LIBRARY STB_INCLUDE_DIR)
mark_as_advanced(STB_INCLUDE_DIR)